### ISSUE TITLE
Inference on multi-targeting not working

### ISSUE THREAD

**Issue by mkaring** [nirin/msbuild-sdks#3]
Hello,

I noticed that any function that relies on changing the `<TargetFramework>` property is not working when using multi-targeting.

If you write in the *.*proj file something like: `<TargetFrameworks>net;net-client</TargetFrameworks> it should resolve to .NET Framework 4.5 and .NET 4.0 - Client, but it fails all together.

The reason for this is the way MSBuild is called, when using multi targeting. The `<MSBuild>` gets the `TargetFramework` using the `Properties` attribute. It seems this launches MSBuild providing this parameter as command line parameter and those command line parameters can't be simply overwritten.

**Comment by Nirmal4G** [comment]
Let me look into this...

**Comment by Nirmal4G** [comment]
I have looked into this, it can be fixed. I'll see what I can do on the NuGet Restore Target side. For now use versioned `TargetFramework`, i.e. use `net45;net40-client` instead of `net;net-client`.

**Comment by Nirmal4G** [comment]
After you fixed your project file, you should see two warnings:

```log
warning MSB3267: The primary reference "System.Net.Http", which is a framework assembly, could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0,Profile=Client". To resolve this problem, either remove the reference "System.Net.Http" or retarget your application to a framework version which contains "System.Net.Http".

warning MSB3052: The parameter to the compiler is invalid, '/define:NET40-CLIENT' will be ignored.
```

You can fix the `MSB3267` by 
```
<ItemGroup>
    <Reference Remove="System.Net.Http">
<ItemGroup>
```

You can fix `MSB3052` by
```
<PropertyGroup Condition="$(TargetFramework.EndsWith('-client'))">
    <ImplicitFrameworkDefine>$(TargetFramework.Replace('-','_').ToUpperInvariant())</ImplicitFrameworkDefine>
    <DisableImplicitFrameworkDefines>true</DisableImplicitFrameworkDefines>
</PropertyGroup>
```
