### ISSUE TITLE
VisualBasic: WPF ApplicationDefinition

### ISSUE THREAD

**Issue by mkaring** [nirin/msbuild-sdks#6]
Hello,

it seems the `ApplicationDefinition` is not properly handled für VisualBasic. C# creates this file with the name "App.xaml", but Visual Basic projects are created with it being named "Application.xaml".

Your test projects show the differently created file. How ever for the VisualBasic projects the "Page" build action is applied.

**Comment by mkaring** [comment]
I think this issue is caused by the DefaultItems and the include order. I fixed the includes this additional SDK in my test projects and it resolved the issue.

**Comment by Nirmal4G** [comment]
Related to #5

**Comment by Nirmal4G** [comment]
I have updated the SDKs on myget, you can test with those. You can find the MyGet links on [ReadMe](../blob/master/ReadMe.md)
